vich_uploader:
    db_driver: orm

    mappings:
        books:
            uri_prefix: /assets/images/books
            upload_destination: '%kernel.project_dir%/public/assets/images/books'
#            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        merchandise:
            uri_prefix: /assets/images/merchandise
            upload_destination: '%kernel.project_dir%/public/assets/images/merchandise'
#            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        upload:
            uri_prefix: /assets/upload
            upload_destination: '%kernel.project_dir%/public/assets/upload'
#            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
