vich_uploader:
    db_driver: orm

    mappings:
        books:
            uri_prefix: /assets/images/books
            upload_destination: '%kernel.project_dir%/public/assets/images/books'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        merchandise:
            uri_prefix: /assets/images/merchandise
            upload_destination: '%kernel.project_dir%/public/assets/images/merchandise'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
